baseurl: https://www.flyingwhale.site

languageCode: zh-cn
paginate: 5
title: FlyingWhale's Blog

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
hasCJKLanguage: true
disqusShortname: hugo-theme-stack
Copyright: '<a href="https://beian.miit.gov.cn/" target="_blank">ICP备案号：赣ICP备2022000922号</a>'

# 本地下载go module时使用
# module:
#   proxy: https://goproxy.cn

