baseurl: https://www.flyingwhale.site

languageCode: zh-cn
paginate: 5
title: FlyingWhale's Blog

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
hasCJKLanguage: true
disqusShortname: hugo-theme-stack

params:
  # 是否显示备案号
  ChinaBeianNumber: 赣ICP备2022000922号

# 本地下载go module时使用
# module:
#   proxy: https://goproxy.cn

